kind: pipeline
type: docker
name: default

steps:
- name: frontend
  image: node:14.18-alpine
  commands:
  - npm install
  - npm run build

- name: scp files
  image: appleboy/drone-scp
  settings:
    host: 192.168.1.75
    user: 
      from_secret: ssh_username
    password: 
      from_secret: ssh_password
    target: /var/www/mark-notes
    source: build/*
    rm: true
